# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
canonifyURLs = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "journeyoftheaverageguy@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

defaultContentLanguage = 'vi'
defaultContentLanguageInSubdir = true
[Languages]
[Languages.vi]
title = "One Observability Workshop"
weight = 1
languageName = "Tiếng Việt"

[Languages.en]
disabled = true
title = "Upload file to AWS S3 through AWS Lambda(Golang)"
weight = 2
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

